# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\x07\n\x05\x45mpty\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"<\n\x0cUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"-\n\x08UserList\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.user.UserResponse2m\n\x0bUserService\x12\x32\n\x07GetUser\x12\x11.user.UserRequest\x1a\x12.user.UserResponse\"\x00\x12*\n\tListUsers\x12\x0b.user.Empty\x1a\x0e.user.UserList\"\x00\x42\x08Z\x06./userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006./user'
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_USERREQUEST']._serialized_start=29
  _globals['_USERREQUEST']._serialized_end=59
  _globals['_USERRESPONSE']._serialized_start=61
  _globals['_USERRESPONSE']._serialized_end=121
  _globals['_USERLIST']._serialized_start=123
  _globals['_USERLIST']._serialized_end=168
  _globals['_USERSERVICE']._serialized_start=170
  _globals['_USERSERVICE']._serialized_end=279
# @@protoc_insertion_point(module_scope)
